apiVersion: v1
kind: Service
metadata:
  name: {{ include "ton3s.fullname" . }}-frontend
  labels:
    {{- include "ton3s.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "ton3s.frontend.selectorLabels" . | nindent 4 }}
