apiVersion: v1
kind: Service
metadata:
  name: {{ include "ton3s.fullname" . }}-backend
  labels:
    {{- include "ton3s.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3001
      protocol: TCP
  selector:
    {{- include "ton3s.backend.selectorLabels" . | nindent 4 }}
